#!/bin/sh

# Config begins

# Passwords - don't commit & push :)
ROOT_PASSWORD="2580"
WIFI_PASSWORD="1234567890"

# Is it a hotspot?
IS_HOTSPOT="false"
GATEWAY="192.168.1.1"

# SQM config
DOWNLOAD_SPEED="0"
UPLOAD_SPEED="16000"

# General config
HOSTNAME="Router"
DESCRIPTION="Routes packets and provides WiFi!"
ZONENAME="Europe/Warsaw"
TIMEZONE="CET-1CEST,M3.5.0,M10.5.0/3"
THEME="bootstrap-dark"

# LAN config
ADDRESS="192.168.1.1"

DNS_1="1.1.1.1"
DNS_2="1.0.0.1"
DNS6_1="2606:4700:4700::1111"
DNS6_2="2606:4700:4700::1001"

# WiFi config
SSID="Fiber"
MOBILITY_DOMAIN="abba"
G2_CHANNEL="1"
G5_CHANNEL="36"
G2_MODE="HE20"
G5_MODE="HE80"

# Config ends

# System info
uci set system.@system[0].hostname="$HOSTNAME"
uci set system.@system[0].description="$DESCRIPTION"
uci set system.@system[0].zonename="$ZONENAME"
uci set system.@system[0].timezone="$TIMEZONE"

# Root password
echo -e "$ROOT_PASSWORD\n$ROOT_PASSWORD" | passwd

# LUCI theme
uci set luci.main.mediaurlbase="/luci-static/$THEME"

# Redirect to HTTPS
uci set uhttpd.main.redirect_https="on"

# LAN interface
uci set network.lan.ipaddr="$ADDRESS"

uci add_list dhcp.lan.dhcp_option="6,$DNS_1,$DNS_2"
uci add_list dhcp.lan.dns="$DNS6_1"
uci add_list dhcp.lan.dns="$DNS6_2"

# WAN interface
uci set network.wan.peerdns="0"
uci add_list network.wan.dns="$DNS_1"
uci add_list network.wan.dns="$DNS_2"

# WAN6 interface
uci set network.wan6.peerdns="0"
uci add_list network.wan6.dns="$DNS6_1"
uci add_list network.wan6.dns="$DNS6_2"

# WiFi 2G
uci set wireless.default_radio0.ssid="$SSID"
uci set wireless.radio0.channel="$G2_CHANNEL"
uci set wireless.radio0.htmode="$G2_MODE"

uci set wireless.default_radio0.encryption="sae-mixed"
uci set wireless.default_radio0.key="$WIFI_PASSWORD"

uci set wireless.default_radio0.ieee80211r="1"
uci set wireless.default_radio0.ft_over_ds="1"
uci set wireless.default_radio0.ft_psk_generate_local="1"
uci set wireless.default_radio0.mobility_domain="$MOBILITY_DOMAIN"

uci set wireless.radio0.disabled="0"

# WiFi 5G
uci set wireless.default_radio1.ssid="$SSID"
uci set wireless.radio1.channel="$G5_CHANNEL"
uci set wireless.radio1.htmode="$G5_MODE"

uci set wireless.default_radio1.encryption="sae-mixed"
uci set wireless.default_radio1.key="$WIFI_PASSWORD"


uci set wireless.default_radio1.ieee80211r="1"
uci set wireless.default_radio1.ft_over_ds="1"
uci set wireless.default_radio1.ft_psk_generate_local="1"
uci set wireless.default_radio1.mobility_domain="$MOBILITY_DOMAIN"

uci set wireless.radio1.disabled="0"

# SQM
uci set sqm.eth1.enabled="1"
uci set sqm.eth1.interface="wan"
uci set sqm.eth1.download="$DOWNLOAD_SPEED"
uci set sqm.eth1.upload="$UPLOAD_SPEED"

# Conditional stuff
if [ "$IS_HOTSPOT" == "true" ]; then
    /etc/init.d/sqm disable
    /etc/init.d/sqm stop

    /etc/init.d/dnsmasq disable
    /etc/init.d/dnsmasq stop

    /etc/init.d/odhcpd disable
    /etc/init.d/odhcpd stop

    uci set dhcp.lan.ignore="1"
    uci set network.wan.auto="0"
    uci set network.wan6.auto="0"

    uci set network.lan.gateway="$GATEWAY"
    uci add_list network.lan.dns="$GATEWAY"
fi

# Apply changes
uci commit

# Reload stuff
/etc/init.d/network reload
/etc/init.d/sqm reload

# The end
exit 0
