#!/bin/bash

# Does the build strictly require "make clean" (e.g. because it's a different device)?
# Ensure that arguments to "build.sh" are in the correct order
# For example: if you have 2 DEV1 devices and 1 DEV2 device, pass both DEV1 profiles to build.sh first and then the DEV2 profile (if you pass DEV1-cnf, DEV2-cnf, DEV1-cnf, you'd have to clean before each build)
REQUIRES_CLEAN=false

### Image config

# Addresses
ADDRESS="192.168.1.1/24"
HOSTNAME="Router"
IS_AP="false"

# WiFi - 2GHz
CHANNEL_2G="1"
MODE_2G="HE20"
RADIO_2G="0"

# WiFi - 5GHz
CHANNEL_5G="36"
MODE_5G="HE160"
RADIO_5G="1"

# WiFi - legacy
LEGACY="true"
SSID_LEGACY="Legacy-1"
ENABLE_2G_LEGACY="true"
ENABLE_5G_LEGACY="false"

# Hardware Ports
WAN_PORT="wan" # Physical WAN port name for this specific device

# Target device
RELEASE="25.12.3"
TARGET="mediatek/filogic"
PROFILE="xiaomi_redmi-router-ax6000-stock"

# Packages only for this device
EXTRA_PACKAGES=""

# Packages removed only from this device
EXTRA_REMOVED=""

###
